### Use Balacne
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId":1,
  "accountNumber":"1000000002",
  "amount":100
}

### Use Balacne2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId":1,
  "accountNumber":"1000000002",
  "amount":100
}

### Cancel Balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId":"2be5479827d04e08b0418364c07e215b",
  "accountNumber":"1000000000",
  "amount":1000
}

### Query Transaction
GET http://localhost:8080/transaction/7ee83133f2d54dab8c56dec46db1b11d